name: Auto Release Tool by Intuit
author: mbround18
description: Run Auto by Intuit on your repo
branding:
  icon: arrow-up
  color: purple
inputs:
  jqVersion:
    description: "Version if jq to use"
    required: true
    default: "1.6"
  autoVersion:
    description: "Version of auto to install"
    required: true
    default: "latest"
  token:
    description: "Admin Pat to use"
    required: true
  command:
    description: "Auto command to run"
    required: true
    default: "shipit -v"
outputs:
  version:
    description: "Outputs the auto version."
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Setup Bins
      shell: sh
      run: |
        . "${GITHUB_ACTION_PATH}/scripts/setup.sh"
        setup_bin

    - name: Setup JQ
      shell: sh
      if: inputs.autoVersion == 'latest'
      run: |
        . "${GITHUB_ACTION_PATH}/scripts/setup.sh"
        setup_jq "${{ inputs.jqVersion }}"

    - name: Get Auto Version
      id: auto_version
      shell: sh
      run: |
        . "${GITHUB_ACTION_PATH}/scripts/utils.sh"

        VERSION="${{ inputs.autoVersion }}"

        if [ "${VERSION}" = "latest" ]; then
          LATEST_TAG="$(getLatestVersion "intuit" "auto")"
          VERSION=${LATEST_TAG}
        fi

        echo "auto_version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Cache Auto Version
      id: cache-auto
      uses: actions/cache@v4
      with:
        path: "${{ env.GITHUB_ACTION_PATH }}/.bin"
        key: ${{ steps.auto_version.outputs.auto_version }}-${{ inputs.jqVersion }}

    - name: Setup Auto
      shell: sh
      if: steps.cache-auto.outputs.cache-hit != 'true'
      run: |
        . "${GITHUB_ACTION_PATH}/scripts/setup.sh"
        setup_auto "${{ steps.auto_version.outputs.auto_version }}"

    - name: Run Auto
      id: auto
      shell: bash
      env:
        GH_TOKEN: "${{ inputs.token }}"
      run: . "${GITHUB_ACTION_PATH}/scripts/exec_auto.sh" "${{ inputs.command }}"

    - name: Parse Version
      shell: bash
      id: version
      run: |
        VERSION="$(. "${GITHUB_ACTION_PATH}/scripts/parse.sh")"
        if [ ! -z "${VERSION}" ]; then
          {
              echo "## Auto Action"
              echo "Release Version: \`${VERSION:-"unknown"}\`"
          } >> $GITHUB_STEP_SUMMARY
          echo "Release Version ${VERSION}"
        fi 
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
